export const FRUIT_KNOWLEDGE_DB = {
  苹果: {
    nutrition: [
      { label: "热量", value: "52kcal", color: "bg-teal-50 border-teal-100" },
      {
        label: "膳食纤维",
        value: "2.4g",
        color: "bg-green-50 border-green-100",
      },
      { label: "维生素C", value: "4mg", color: "bg-amber-50 border-amber-100" },
      { label: "钾", value: "119mg", color: "bg-teal-50 border-teal-100" },
    ],
    pickTips: [
      "选择颜色均匀、有自然光泽的",
      "轻按感觉坚实，不过软也不过硬",
      "果蒂新鲜青绿为佳",
      "闻起来有清香苹果味",
    ],
    suitableFor: [
      "减重人群（低热量）",
      "便秘者（高纤维）",
      "高血压患者（含钾）",
      "一般人群皆宜",
    ],
    avoidFor: ["胃酸过多者宜饭后吃", "糖尿病患者注意分量", "对苹果过敏者避免"],
    storageDays: 7,
    grade: "A",
    desc: "苹果富含膳食纤维和抗氧化物质，有助于消化和增强免疫力。",
  },
  香蕉: {
    nutrition: [
      {
        label: "热量",
        value: "89kcal",
        color: "bg-yellow-50 border-yellow-100",
      },
      {
        label: "碳水化合物",
        value: "22g",
        color: "bg-teal-50 border-teal-100",
      },
      { label: "钾", value: "358mg", color: "bg-teal-50 border-teal-100" },
      {
        label: "维生素B6",
        value: "0.4mg",
        color: "bg-teal-50 border-teal-100",
      },
    ],
    pickTips: [
      "表皮金黄带少量斑点最甜",
      "避免有大量黑斑或裂口",
      "果柄完整不脱落",
      "轻捏有弹性但不过软",
    ],
    suitableFor: [
      "运动员（快速能量）",
      "高血压患者（高钾）",
      "便秘者（促进排便）",
      "需要补充能量者",
    ],
    avoidFor: [
      "肾病患者（高钾需限制）",
      "糖尿病患者注意分量",
      "胃寒者不宜空腹大量吃",
    ],
    storageDays: 3,
    grade: "A",
    desc: "香蕉是优质的快速能量来源，富含钾元素，有助于维持血压稳定。",
  },
  草莓: {
    nutrition: [
      { label: "热量", value: "32kcal", color: "bg-pink-50 border-pink-100" },
      {
        label: "维生素C",
        value: "58mg",
        color: "bg-amber-50 border-amber-100",
      },
      { label: "叶酸", value: "24μg", color: "bg-green-50 border-green-100" },
      { label: "膳食纤维", value: "2g", color: "bg-teal-50 border-teal-100" },
    ],
    pickTips: [
      "颜色鲜红均匀，无白斑",
      "蒂叶翠绿新鲜不枯萎",
      "表面籽粒金黄凸起",
      "闻起来有浓郁果香",
    ],
    suitableFor: [
      "美容养颜者（高VC）",
      "孕妇（富含叶酸）",
      "免疫力低下者",
      "控制体重者",
    ],
    avoidFor: ["肠胃敏感者宜少量", "对草莓过敏者避免", "肾功能不全者注意"],
    storageDays: 2,
    grade: "A+",
    desc: "草莓维生素C含量极高，抗氧化能力强，有助于美白和增强免疫力。",
  },
  橙子: {
    nutrition: [
      {
        label: "热量",
        value: "47kcal",
        color: "bg-orange-50 border-orange-100",
      },
      {
        label: "维生素C",
        value: "53mg",
        color: "bg-amber-50 border-amber-100",
      },
      {
        label: "膳食纤维",
        value: "2.4g",
        color: "bg-green-50 border-green-100",
      },
      { label: "钙", value: "40mg", color: "bg-gray-50 border-gray-100" },
    ],
    pickTips: [
      "表皮细腻光滑有光泽",
      "手感沉重水分足",
      "脐部小且紧实",
      "轻捏有弹性不松软",
    ],
    suitableFor: [
      "感冒预防者（高VC）",
      "皮肤干燥者",
      "便秘者（促进消化）",
      "一般人群",
    ],
    avoidFor: [
      "胃酸过多者宜饭后吃",
      "服药期间避免（影响药效）",
      "对柑橘类过敏者",
    ],
    storageDays: 10,
    grade: "A",
    desc: "橙子富含维生素C和纤维素，有助于提高免疫力和促进消化。",
  },
  葡萄: {
    nutrition: [
      { label: "热量", value: "69kcal", color: "bg-teal-50 border-teal-100" },
      { label: "葡萄糖", value: "15g", color: "bg-pink-50 border-pink-100" },
      { label: "白藜芦醇", value: "高", color: "bg-red-50 border-red-100" },
      { label: "铁", value: "0.4mg", color: "bg-amber-50 border-amber-100" },
    ],
    pickTips: [
      "果粒饱满紧实不脱落",
      "表面有天然白霜为新鲜",
      "颜色均匀无皱缩",
      "整串提起不散落",
    ],
    suitableFor: [
      "贫血者（含铁）",
      "抗氧化需求者",
      "需要快速能量者",
      "心血管保健者",
    ],
    avoidFor: ["糖尿病患者控制分量", "肠胃虚弱者去皮吃", "肾功能不全者注意"],
    storageDays: 5,
    grade: "B+",
    desc: "葡萄富含抗氧化物质白藜芦醇，有助于保护心血管健康。",
  },
  猕猴桃: {
    nutrition: [
      { label: "热量", value: "61kcal", color: "bg-green-50 border-green-100" },
      {
        label: "维生素C",
        value: "92mg",
        color: "bg-amber-50 border-amber-100",
      },
      { label: "膳食纤维", value: "3g", color: "bg-teal-50 border-teal-100" },
      { label: "钾", value: "312mg", color: "bg-teal-50 border-teal-100" },
    ],
    pickTips: [
      "手感微软有弹性",
      "表皮绒毛整齐不脱落",
      "两端圆润不干瘪",
      "闻起来有清香",
    ],
    suitableFor: [
      "免疫力低下者（极高VC）",
      "便秘者（高纤维）",
      "高血压患者",
      "美容养颜者",
    ],
    avoidFor: ["胃酸过多者适量", "腹泻期间避免", "对猕猴桃过敏者"],
    storageDays: 7,
    grade: "A+",
    desc: "猕猴桃是维生素C之王，含量远超橙子，同时富含膳食纤维和钾。",
  },
  芒果: {
    nutrition: [
      {
        label: "热量",
        value: "60kcal",
        color: "bg-yellow-50 border-yellow-100",
      },
      {
        label: "维生素A",
        value: "54μg",
        color: "bg-orange-50 border-orange-100",
      },
      {
        label: "维生素C",
        value: "36mg",
        color: "bg-amber-50 border-amber-100",
      },
      { label: "胡萝卜素", value: "高", color: "bg-red-50 border-red-100" },
    ],
    pickTips: [
      "果皮颜色金黄带红晕",
      "手感微软有弹性",
      "闻起来有浓郁果香",
      "果蒂周围无黑斑",
    ],
    suitableFor: [
      "视力保护者（高维A）",
      "皮肤干燥者",
      "免疫力提升者",
      "一般人群",
    ],
    avoidFor: ["过敏体质者慎食", "糖尿病患者控制分量", "湿热体质者适量"],
    storageDays: 4,
    grade: "A",
    desc: "芒果富含维生素A和胡萝卜素，有助于保护视力和皮肤健康。",
  },
};
